### ISSUE TITLE
About using 'toString(format: .isoYear)'  confusion

### ISSUE THREAD

**Issue by RenSihao** [melvitax/DateHelper#100]
![image](https://user-images.githubusercontent.com/15172591/109133057-86c4b880-778f-11eb-935d-c2875d1f6f64.png)
Xcode Version 12.3 (12C33)
iPhone Simulator 12 ProMax 14.2 (Version 12.3 (940.20))
DataHelper 4.4.1

As shown above,  please noticed results of 'x' and 'x11' (of course i used the same date object instance)

1. why use 'toString(format: .isoYear)' to get a empty string?
2. why use 'toString(format: .isoYear)' and 'toString(format: .custom("yyyy")' to get different output?

**Comment by melvitax** [comment]
Thanks for discovering this. It looks like the ISO8601DateFormatter requires .withFractionalSeconds to render .isoYear properly. I will fix in the next release.

**Comment by melvitax** [comment]
This is now fixed in the 4.5.0 release
