### ISSUE TITLE
Error on build: 'ISO8601DateFormatter' is only available in iOS 10.0 or newer

### ISSUE THREAD

**Issue by Prince2k3** [melvitax/DateHelper#102]
I have a project that is iOS 14 and up. I'm getting a message `'ISO8601DateFormatter' is only available in iOS 10.0 or newer`
The package.swift of the DateHelper says `v9` I'm wondering if it should be at least `v10` if your using the  `ISO8601DateFormatter`

**Comment by CoolONEOfficial** [comment]
#103 fixed

**Comment by wiencheck** [comment]
I am still getting this error on newest 4.5.2 version

**Comment by CoolONEOfficial** [comment]
I've fix that in my pr only

**Comment by hixfield** [comment]
I just did a update to latest packages in Xcode an also got this message. The package is broken now.
It might be fixed in #103 but I should still be properly committed so that people upgrading to the latest package can get their project running (again).

**Comment by jtthrillson** [comment]
With the #103 fix, I'm not getting a similar issue. Now it displays the error `'withFractionalSeconds' is only available in iOS 11.0 or newer`. I opened a new PR #104 increasing iOS to v11 in package.swift.

**Comment by melvitax** [comment]
All included in the latest release. Thanks for the contributions @jtthrillson and @CoolONEOfficial
