### ISSUE TITLE
Need to exclude Info.plist resource from Package.swift to resolve build warning

### ISSUE THREAD

**Issue by atticus** [melvitax/DateHelper#105]
When building with version 4.5.3, I get a warning:

"found 1 file(s) which are unhandled; explicitly declare them as resources or exclude from the target
/[Path snipped]/SourcePackages/checkouts/DateHelper/Sources/Info.plist"

I think the Info.plist resource needs to be excluded from the Package.swift file to resolve the warning.

Here's an example of aws-amplify resolved the same issue:
https://github.com/aws-amplify/amplify-ios/pull/1163/commits/c659a2653caa6351eb578dd7b8defa92af701835

**Comment by logankriete** [comment]
I'm having this same issue. How can I stop Xcode from complaining when building?

**Comment by logankriete** [comment]
@atticus, until my pull request gets merged by @melvitax, feel free to use the patch-1 branch from my repo. Compiles in my version of Xcode 12.5 (12E262) without any warnings.

**Comment by melvitax** [comment]
Thanks @logankriete for providing a fix
