### ISSUE TITLE
... is inaccessible due to 'internal' protection level

### ISSUE THREAD

**Issue by hensch7** [melvitax/DateHelper#112]
Hey,

I get this mistake every time I try to use a method from your library.
Even the most simple construct won't work, because I get an internal protection level error stopping me from compiling.

For example I get the error when trying this: 

Text(Date().toString(format: .isoYear))

![Bildschirmfoto 2022-01-11 um 17 15 00](https://user-images.githubusercontent.com/59776927/148980329-abfd64c3-61ef-4158-88a1-f11708beaf62.png)

Does this has anything to do with the new initializing method you use?
When reverting to 4.5.4 everything works perfectly fine.

Thank you very much in advance!

**Comment by melvitax** [comment]
Ah yes. Just fixed this in a new release.
