### ISSUE TITLE
Int overflow for dates far in the future

### ISSUE THREAD

**Issue by lukeconlon** [melvitax/DateHelper#27]
secondsAfterDate casts the timeIntervalSinceDate result into an Int32 and not an Int64, so results for dates that are far in the future (i.e. 2100-01-01 00:00:00) will overflow 32 bits and cause a crash.

This probably applies to other methods that are implemented similarly to secondsAfterDate.

**Comment by melvitax** [comment]
`func secondsAfterDate(date: NSDate) -> Int
    {
        return Int(self.timeIntervalSinceDate(date))
    }
`
According to documentation Int should cast to a 64bit integer: Int() - A 64-bit signed integer value type. No?

**Comment by melvitax** [comment]
Fixed in 4.0.0 https://github.com/melvitax/DateHelper/commit/26ce7bdb231436617ae1fbccc1568f95584929ca
