### ISSUE TITLE
Validate if the string is correct format

### ISSUE THREAD

**Issue by jsgoupil** [melvitax/DateHelper#34]
Using NSDate.dateFromString allows me to know if my string matches the format. If it doesn't, I get a nil.

With your extension, it should have a way to validate if my string matches a specific format. If it doesn't, give me nil. Right now, it init the date with self.init() giving me today's date...

My goal would be to try out multiple format and return a date once my format is matched. My format can be more than ISO8601 (MVC, RSS, Custom, etc)

**Comment by melvitax** [comment]
Fixed in 4.0.0 https://github.com/melvitax/DateHelper/commit/26ce7bdb231436617ae1fbccc1568f95584929ca
