### ISSUE TITLE
Bug in pull request

### ISSUE THREAD

**Issue by fraserscottmorrison** [melvitax/DateHelper#41]
In Pull request 32, https://github.com/melvitax/AFDateHelper/pull/32

"com.allforces.$(PRODUCT_NAME:rfc1034identifier)" was changed to com.allforces.AFDateHelperDemo;

This causes the App Store to reject the ipa when uploading due to the bundle version being invalid

**Comment by melvitax** [comment]
Let me know if this is still an issue.

**Comment by fraserscottmorrison** [comment]
Im not sure cause I can't use DateHelper with CocoaPods as I need to support iOS8.0. 

Would you be able to release a new CocoaPod version with the new iOS8.0 commit?

**Comment by melvitax** [comment]
Latest version is now on CocoaPods
