### ISSUE TITLE
when day is Sunday, isThisWeek() or isNextWeek() both can be true or false

### ISSUE THREAD

**Issue by ThiagoCamila** [melvitax/DateHelper#47]
e.g:
   date = 10,7,2016 (is Sunday), date.isThisWeek() sometimes return true, sometimes return false, also date.isNextWeek() sometimes return true, sometimes return false. I call this in tableView scroll will change. I print my log as follows: (in China, UTC+8, see 2016-07-09)
------2016-08-28 09:41:36 +0000, thisWeek:false, nextWeek:false
**------2016-07-09 16:00:00 +0000, thisWeek:true, nextWeek:false**
------2016-07-29 16:00:00 +0000, thisWeek:false, nextWeek:false
------2016-08-28 09:41:36 +0000, thisWeek:false, nextWeek:false
------2016-08-28 09:41:36 +0000, thisWeek:false, nextWeek:false
------2016-07-29 16:00:00 +0000, thisWeek:false, nextWeek:false
**------2016-07-09 16:00:00 +0000, thisWeek:false, nextWeek:true**
------2016-08-28 09:41:36 +0000, thisWeek:false, nextWeek:false

**Comment by melvitax** [comment]
Can you include the rest of your code? I would like to see if this an issue with caching or something else in your code.

**Comment by melvitax** [comment]
Closing this since I haven't heard back
