### ISSUE TITLE
Swift 3.0 compatibility

### ISSUE THREAD

**Issue by LivioGama** [melvitax/DateHelper#53]
Hi,

You forgot to push v3.5.0 to Cocoapods. Project doesn't compile with 3.4.2

**Comment by kaunteya** [comment]
Please push 3.5.0 asap

**Comment by melvitax** [comment]
I keep having issues with cocoa pods not passing lint test so please download manually in the meantime.

**Comment by dlpigpen** [comment]
year got the same issue, can you push the branch swift 3 to cocoapod?

**Comment by LivioGama** [comment]
I managed to make it work by putting "Use legacy Swift language version" to YES in Build Settings of the pod

**Comment by melvitax** [comment]
got it working now
