### ISSUE TITLE
dateAtStart/EndOfWeek don't account for year boundaries

### ISSUE THREAD

**Issue by MahatmaManic** [melvitax/DateHelper#58]
dateAtStartOfWeek and dateAtEndOfWeek blow up if on a week that straddles New Year

**Comment by shawnwall** [comment]
+1

**Comment by coolioxlr** [comment]
+1

**Comment by melvitax** [comment]
Can you give me some sample dates to test against?

**Comment by melvitax** [comment]
Fixed computation in this commit https://github.com/melvitax/DateHelper/commit/0e68b49687d659fded446fd1c9f76edd2e2585a2
