### ISSUE TITLE
Support for iOS8.0

### ISSUE THREAD

**Issue by fraserscottmorrison** [melvitax/DateHelper#59]
Your pod file limits support to iOS8.4+, but lots of projects still need to support iOS8.0+

Ive had to copy you DateHelper file to my project rather than using CocoaPods, but it'd be really easy for you to change the Podfile to support iOS8.0

There are a number of forks that have done this, so Im not alone here
Cheers

**Comment by ben-j69** [comment]
👍

**Comment by thonydam** [comment]
+1

**Comment by fraserscottmorrison** [comment]
Thanks for looking into - Can you push out a new CocoaPod version with this change?
