### ISSUE TITLE
toString(.shortMonth) doesn't work properly

### ISSUE THREAD

**Issue by emirhb** [melvitax/DateHelper#62]
In DateHelper.swift
    func toString(style:DateStyleType = .short) -> String

has a issue.

        case .month:
            let monthSymbols = Date.cachedFormatter().monthSymbols!
            return monthSymbols[component(.**weekday**)!-1] as String **_// should be month_**
        case .shortMonth:
            let shortMonthSymbols = Date.cachedFormatter().shortMonthSymbols!
            return shortMonthSymbols[component(.**weekday**)!-1] as String **_// should be month_**
        case .veryShortMonth:
            let veryShortMonthSymbols = Date.cachedFormatter().veryShortMonthSymbols!
            return veryShortMonthSymbols[component(.**weekday**)!-1] as String **_// should be month_**

**Comment by melvitax** [comment]
Thanks for catching this bug. It's been fixed here: https://github.com/melvitax/DateHelper/commit/edb0c6e2357830572e0e3a500f9ab48955ddbc97
