### ISSUE TITLE
No scheme for Mac setup

### ISSUE THREAD

**Issue by MattesGroeger** [melvitax/DateHelper#64]
Hi, I'm trying to build your library with Carthage for `Mac` (not iOS). Unfortunately there is no scheme set up for `Mac`.

Error:

```
Dependency "DateHelper" has no shared framework schemes for any of the platforms: Mac
```

**Comment by melvitax** [comment]
I just added a framework for mac but I don't really do Mac development. Could you test it out for me? I got an error with cocoa pods I'm not sure how to resolve.
