### ISSUE TITLE
Day Suffix

### ISSUE THREAD

**Issue by Chazzman** [melvitax/DateHelper#65]
Might be nice to add a day suffix to the library. Something like:

`extension Date {

    static func getSuffix(forDate date: Date) -> String {
        if let day = date.component(.day) {
            let st: Set = [1, 21, 31]
            let nd: Set = [2, 22]
            let rd: Set = [3, 23]
            if st.contains(day) {
                return "st"
            }
            else if nd.contains(day) {
                return "nd"
            }
            else if rd.contains(day) {
                return "rd"
            }
            else {
                return "th"
            }
        } else {
            return ""
        }
    }
}`

Thanks!

**Comment by melvitax** [comment]
I just added it as a new style format:
now.toString(style: .ordinalDay) 
should yield 27th i.e.

**Comment by Chazzman** [comment]
Awesome

Thanks

Any idea as to why the pod doesn't seem to work? Update pull 4.1.2 but the changes aren't there. Tried deleting and reinstalling. No errors but not new code either :(

**Comment by melvitax** [comment]
Cocoapods fixed now

**Comment by Chazzman** [comment]
Hmmm

Still not pulling

**Comment by melvitax** [comment]
Ah yes, sorry I fixed the pod lint issue but forgot to push to cocoa pods trunk. It's updated now.

**Comment by Chazzman** [comment]
That did the trick!

Thanks again!
