### ISSUE TITLE
init Date fromString returns nil when 2017-10-15

### ISSUE THREAD

**Issue by fabiwerneck** [melvitax/DateHelper#66]
Even w/ `format: .custom` it returns nil.

![afdate_error](https://user-images.githubusercontent.com/3869458/27763684-5ed058d2-5e5e-11e7-8bfa-916bfb1132b6.png)

**Comment by m3rLin0WoRK** [comment]
same issue with 1972-05-28

**Comment by m3rLin0WoRK** [comment]
Ok, I have found solution.

On daylight saving dates the parser return nil. 2017-10-15 in Brazil for example at 00:00 is an invalid date.

You can patch this with isLenient flag enabled or pass date with valid hour.

**Comment by melvitax** [comment]
@m3rLin0WoRK  Let me know if this fixes your issue

**Comment by m3rLin0WoRK** [comment]
Yes this work, but be careful because an invalid date like 2017-02-30 return a valid Date (first of March) that in certain cases could not be the desired result.
