### ISSUE TITLE
Use pod_target_xcconfig instead of xcconfig in the podspec

### ISSUE THREAD

**Issue by mkval** [melvitax/DateHelper#68]
Hi there, 

First of all, thanks for this awesome library. :)

After adding it to my project via CocoaPods, I noticed some warnings for both Debug and Release configs:

```
[!] The `MyProject [Debug]` target overrides the `SWIFT_VERSION` build setting defined in `Pods/Target Support Files/Pods-MyProject/Pods-MyProject.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `MyProject [Release]` target overrides the `SWIFT_VERSION` build setting defined in `Pods/Target Support Files/Pods-MyProject/Pods-MyProject.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
```

Googling led me to CP's Github page that [detailed the issue](https://github.com/CocoaPods/CocoaPods/issues/5952). The advice they gave was to file an issue with the Pod suggesting the usage of `pod_target_xcconfig` instead of `xcconfig` in the `podspec`. 

Here's a [detailed report](https://github.com/CocoaLumberjack/CocoaLumberjack/issues/814) made by one of CP's maintainers. 

Thanks.

**Comment by weakfl** [comment]
+1

**Comment by melvitax** [comment]
Thanks for the heads up.  Fixed here: https://github.com/melvitax/DateHelper/commit/fcdbd2f8e91952aaf57fe437b167d15e980c58bb

**Comment by mkval** [comment]
Thanks @melvitax
