### ISSUE TITLE
Error 'range(at:)' has been renamed to 'rangeAt(_:)'

### ISSUE THREAD

**Issue by emonster** [melvitax/DateHelper#72]
I get this error every time I update pods
line 34 in DateHelper.swift
.../Pods/AFDateHelper/Sources/DateHelper.swift:34:77: 'range(at:)' has been renamed to 'rangeAt(_:)'

**let dateString = (string as NSString).substring(with: match.range(at: 1))**
Update to 
**let dateString = (string as NSString).substring(with: match.rangeAt(1))**
then it is ok...

**Comment by evermeer** [comment]
I had a similar problem and even this did not work:

        #if swift(>=4.0)
            let dateString = (fromDateTimeString as NSString).substring(with: match.range(at: 1))     // Extract milliseconds
        #else
            let dateString = (fromDateTimeString as NSString).substring(with: match.rangeAt(1))     // Extract milliseconds
        #endif

**Comment by evermeer** [comment]
For now I have Eliminated the use of `range(at:` bij changing my function to

    public init?(fromDateTimeString: String) {
        let pattern = "\\\\?/Date\\((\\d+)(([+-]\\d{2})(\\d{2}))?\\)\\\\?/"
        let regex = try! NSRegularExpression(pattern: pattern)
        let match: NSRange = regex.rangeOfFirstMatch(in: fromDateTimeString, range: NSRange(location: 0, length: fromDateTimeString.utf16.count))
        var dateString: String = ""
        if match.location == NSNotFound {
            dateString = fromDateTimeString
        } else {
            dateString = (fromDateTimeString as NSString).substring(with: match)     // Extract milliseconds
        }
        let substrings = dateString.components(separatedBy: CharacterSet.decimalDigits.inverted)
        guard let timeStamp = (substrings.flatMap { Double($0) }.first) else { return nil }
        self.init(timeIntervalSince1970: timeStamp / 1000.0) // Create Date from timestamp
    }

**Comment by melvitax** [comment]
Fixed with an if statement:
https://github.com/melvitax/DateHelper/commit/910047590b8806dac5041f9e0b59995927cb5616
