### ISSUE TITLE
Date incorrect when raw

### ISSUE THREAD

**Issue by Ged2323** [melvitax/DateHelper#77]
Hi,
I have saved a date yesterday and it reads -- 2018-04-11 21:09:27 +0000

Though today I printed todays date which should be  2018-04-12 21:09:27 +0000
reads → 2018-04-11 21:59:18 +0000

This is fixed when I print it to a string but it is not correct when working with the raw" Date".
I'm trying to compare the date I saved yesterday to today and it returns it is the same day.

Thanks in advance for your help.

**Comment by melvitax** [comment]
Could you provide the code and comment it?

**Comment by Ged2323** [comment]
```swift
  let now = Date()
// I saved this to user defaults yesterday
  let dateSaved = userDefaults.value(forKey: dateSavedKey) as! Date
  print("dateSaved—> \(dateSaved)\n")
  print("now—> \(now)\n")
```

This is printing.

dateSaved—> 2018-04-11 21:09:27 +0000

now—> 2018-04-11 23:29:26 +0000

**Comment by melvitax** [comment]
So the issue is with the creation of that seed date. Hard to say unless I know hoe you created it.

**Comment by Ged2323** [comment]
I've got the DateHelper.swift file in a commandLine Xcode project.
[DateHelper.swift.zip](https://github.com/melvitax/DateHelper/files/1900947/DateHelper.swift.zip)

And I'm just calling this in main.

Date() would be calling the ext in the DateHelper.swift file right?

I have over written the saved date in user defaults though when I save the seed date its this:

dateSaved—> 2018-04-12 01:00:01 +0000

now—> 2018-04-12 01:03:15 +0000

Why does it say 1:00 when it is 11 here?  Is that right?

**Comment by melvitax** [comment]
Time zones.
For example in Los Angeles it is Apr 12, 2018 at 9:32 AM.
`
let date = Date()
print(date)
`
should print the etc time stamp: 2018-04-12 16:32:30 +0000
But if we use of one DateHelper date to string functions we can get a localized time 
`
date.toString(style: .medium)
`
should print: Apr 12, 2018 at 9:32:30 AM
