### ISSUE TITLE
How do you use the "custom" tuple? 

### ISSUE THREAD

**Issue by justdan0227** [melvitax/DateHelper#79]
Can I get an example of using the custom tuple to create a date?

case custom(String): a custom date format string

**Comment by melvitax** [comment]
`Date().toString(format: .custom("MMM d, yyyy"))
 Date().toString(format: .custom("h:mm a"))
 Date().toString(format: .custom("MMM d"))
 Date().toString(format: .custom("MMM d"))
 Date().toString(format: .custom("E MMM d"))`
I'll be adding some in the domination in the next release. You can use the component guide in the read me as a guide.
