### ISSUE TITLE
Xcode 10, Apple Watch (arm64_32) minimum deployment

### ISSUE THREAD

**Issue by Sweefties** [melvitax/DateHelper#82]
`This bundle is invalid. Applications built for more than one architecture require an iOS Deployment Target of 3.0 or later.`

You have to set the deployment target for all watchOS targets (although it says iOS) to 3.0 or higher..

By upload to App Store Connect we have one error to minimumOS deployment. It's ok after editing your info.plist file (Carthage build watchOS) to 3.0.

**Comment by melvitax** [comment]
Updating now
