### ISSUE TITLE
.endOfWeek does not handler a calendar with firstWeekDay set to anything other than default

### ISSUE THREAD

**Issue by jem5519** [melvitax/DateHelper#88]
Looking at dateHelper.siwft lines 367 - 370:

     
`case .startOfWeek:
            return calendar.date(from: calendar.dateComponents([.yearForWeekOfYear, .weekOfYear], from: self))!`
        
`case .endOfWeek:
            let offset = 7 - component(.weekday)!`

note: "case .endOfWeek:"  does not include the value of calendar

Consider replacing line 370 with:

`return calendar.date(from: calendar.dateComponents([.yearForWeekOfYear, .weekOfYear], from: self))!.adjust(.day, offset: 6)`

**Comment by sharedRoutine** [comment]
I‘d rather replace it with:

let weekStart = self.dateFor(.startOfWeek, calendar: calendar)
return weekStart.adjust(.day, offset: 6)

**Comment by melvitax** [comment]
This is now fixed in the 4.5.0 release
