### ISSUE TITLE
date from string saving wrong date

### ISSUE THREAD

**Issue by ProfoundDonut** [melvitax/DateHelper#93]
I'm saving a date, and then converting it to a string.  It however displays a date from last year.

Here is my code:
```swift
let date = Date(fromString: dateval, format: .custom("MM/dd/YYYY"))
```
`dateval` is downloaded from a server, and is equal to `12/21/2019`

The output of 
```swift
 date.toString()
```
is `12/23/18, 12:00 AM`

Thanks in advance for any help!

**Comment by ThiagoCamila** [comment]
Word Why? My math
Max Simon <notifications@github.com> 于 2019年12月21日周六 10:35写道：
