### ISSUE TITLE
Feature Request: Allow checking the RelativeTimeStringType of a Date

### ISSUE THREAD

**Issue by emma-k-alexandra** [melvitax/DateHelper#94]
Currently [toStringWithRelativeTime](https://github.com/melvitax/DateHelper/blob/f3c896beb529e86eba46483121276c74390856de/Sources/DateHelper.swift#L123) uses `RelativeTimeStringType` to output Strings. However, there is no way to determine which `RelativeTimeStringType` a `Date` falls into without looking at the output string of `toStringWithRelativeTime`.

It would be nice to be able to get the `RelativeTimeStringType` of a `Date` directly with something like

```swift
Date().toRelativeTime() // .nowPast
```

or

```swift
Date().is(.nowPast) // true
```

This could allow for additional logic switching off of the `RelativeTimeStringType` of a `Date`, rather than just converting to a String.

**Comment by emma-k-alexandra** [comment]
Currently working on a PR if interested

**Comment by emma-k-alexandra** [comment]
Note that this PR slightly reduces the performance of `toStringWithRelativeTime` due to duplicating operations with `toRelativeTime`

**Comment by melvitax** [comment]
Thanks
