### ISSUE TITLE
Not able to build with Xcode 12

### ISSUE THREAD

**Issue by shireesh1993** [melvitax/DateHelper#99]
<img width="939" alt="Screenshot 2020-11-02 at 12 32 48 PM" src="https://user-images.githubusercontent.com/73632311/97839105-864b7200-1d07-11eb-83a2-e4e38e26096b.png">

Please let me know how can I fix this .

I have tried few ways to  get rid of like keychain Login lock and Unlock ,Updating the pods,Updating the cocoa pods but found no luck .

**Comment by hassan8357** [comment]
I've the same issue here. Any updates?!! @melvitax

**Comment by Sikandarkhan** [comment]
Did anyone find the solution yet?

**Comment by melvitax** [comment]
How are you guys installing DateHelper? I've been running in Xcode 12 since the beta with no issues. I haven't updated Cocoapods in a few versions and plan to deprecated in the next release. Please use Swift Package Manager or Carthage.

**Comment by wolfcon** [comment]
@melvitax Why not support `CocoaPods`? Just simple as it is.

**Comment by melvitax** [comment]
Cocoapods is now. considered legacy. I'm including a "if #available(iOS 10.0" check for picking the right date formatter.

**Comment by wolfcon** [comment]
Well. noted..
